[project]
author = "The Legendary ControlCplusControlV"
license = "Apache-2.0"
name = "CopiedSway"
entry = "lib.sw"

[dependencies]
core = { git = "http://github.com/FuelLabs/sway-lib-core" }
std = { git = "http://github.com/FuelLabs/sway-lib-std" }
